name: gmstest
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '3.3.3'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  get: ^4.6.5
  davi: ^3.4.1
  http: ^1.1.2
  shared_preferences: ^2.2.2
  intl: ^0.17.0
  flutter_svg: ^2.0.9
  google_fonts: ^6.1.0
  carousel_slider: ^4.2.1
  charts_flutter: ^0.12.0
  fl_chart: ^0.66.2
  lottie: ^3.1.0
  pie_chart: ^5.4.0
  file_picker: ^8.0.0+1
  image_picker_for_web: ^3.0.2
  flutter_image_compress: ^2.2.0
  image: ^4.1.7
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icon/
    - assets/animations/
